"""Checks on the schema itself.

Deliberately short. Testing that databases honour unique constraints is testing
somebody else's code. Each test here covers something this project could get
wrong on its own:

* the migrations drifting away from the models
* foreign key checking being off, which is SQLite's default
* the end date check constraint being written so it also rejects open ended
  requests
"""

from __future__ import annotations

import uuid
from datetime import date

import pytest
from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm import Session

from app.domain.enums import MedicationForm, MedicationRequestStatus, Sex
from app.models import Clinician, Medication, MedicationRequest, Patient


def test_models_and_migrations_have_not_drifted(alembic_config: Config) -> None:
    """``alembic check`` fails if the models describe a schema the migrations do not build."""
    try:
        command.check(alembic_config)
    except AutogenerateDiffsDetected as drift:
        pytest.fail(f"Models and migrations are out of sync: {drift}")


def make_reference_rows(session: Session) -> tuple[Patient, Clinician, Medication]:
    """Insert one of each thing a medication request needs to point at."""
    patient = Patient(
        first_name="Ada",
        last_name="Lovelace",
        date_of_birth=date(1975, 12, 10),
        sex=Sex.FEMALE,
    )
    clinician = Clinician(
        first_name="Elinor",
        last_name="Ostrom",
        registration_id=f"REG-{uuid.uuid4().hex[:8]}",
    )
    medication = Medication(
        code=uuid.uuid4().hex[:8],
        code_name="Oxamniquine",
        code_system="SNOMED",
        strength_value=250,
        strength_unit="mg",
        form=MedicationForm.CAPSULE,
    )
    session.add_all([patient, clinician, medication])
    session.flush()
    return patient, clinician, medication


def test_foreign_keys_are_enforced(db_session: Session) -> None:
    """SQLite ignores foreign keys unless asked not to, so this guards the engine setup."""
    patient, _, medication = make_reference_rows(db_session)

    db_session.add(
        MedicationRequest(
            patient_id=patient.id,
            clinician_id=uuid.uuid4(),
            medication_id=medication.id,
            prescribed_date=date(2026, 1, 5),
            start_date=date(2026, 1, 6),
            status=MedicationRequestStatus.ACTIVE,
        )
    )

    with pytest.raises(IntegrityError):
        db_session.flush()


def test_end_date_cannot_be_before_start_date(db_session: Session) -> None:
    """The domain layer checks this too. The database is the backstop."""
    patient, clinician, medication = make_reference_rows(db_session)

    db_session.add(
        MedicationRequest(
            patient_id=patient.id,
            clinician_id=clinician.id,
            medication_id=medication.id,
            prescribed_date=date(2026, 1, 5),
            start_date=date(2026, 1, 10),
            end_date=date(2026, 1, 9),
            status=MedicationRequestStatus.ACTIVE,
        )
    )

    with pytest.raises(IntegrityError):
        db_session.flush()


def test_an_open_ended_request_is_still_allowed(db_session: Session) -> None:
    """A naive end_date >= start_date check would reject every null end date."""
    patient, clinician, medication = make_reference_rows(db_session)

    db_session.add(
        MedicationRequest(
            patient_id=patient.id,
            clinician_id=clinician.id,
            medication_id=medication.id,
            prescribed_date=date(2026, 1, 5),
            start_date=date(2026, 1, 6),
            end_date=None,
            status=MedicationRequestStatus.ACTIVE,
        )
    )

    db_session.flush()
